
--	...........................................................................
--	第一版在上海完成
--
--	2019-06-10 13:39, tian-an 601, wujianhua
--	rev.2
--
--	GWALL 是一种由多个点围起来的面拉伸的墙体（实体）
--
--	...........................................................................

!this		= !!CE
!currENT	= !!CE

!X = 1

do !X
	--	直到 SITE 层
	break	if ( !this.type  EQ  'SITE' )
--	break	if ( !this.type  EQ  'ZONE' )

	!!CE	= !!CE.owner
	!this	= !!CE

enddo

--	............................................................................

VAR !listgwall COLL ALL	gwall	FOR CE  

--	Q VAR !wallist

!pathname = |D:\123-PDMS|

!swriter = object FILE(  !pathname + '\pdms-Gwall-list.xml' )
!swriter.open( 'WRITE' )

!swriter.writerecord( '<?xml version="1.0" encoding="utf-8" ?>' )
!swriter.writerecord( '<ListGWall>' )

do  !nname  values  !listgwall

	!gwall	= !nname.DBREF()
	!post	= !gwall.position.wrt( world )
	!vect	= !gwall.orientation.wrt( world )

	!swriter.writerecord( '<GWall>'		)
	
	!swriter.writerecord( !!wuXmlString(		|Name|, 		!gwall.name 		) )
	!swriter.writerecord( !!wuXmlString(		|Vati-Name|, 	!gwall.owner.name	) )
	!swriter.writerecord( !!wuXmlString(		|Vati-Type|, 	!gwall.owner.type	) )
	!swriter.writerecord( !!wuXmlPoint(	 		|Position|,		!post				) )
	!swriter.writerecord( !!wuXmlOrientation( 	|Orientation|,	!vect				) )
	
	!listsohn = !gwall.members

	do !plname values !listsohn

		!ptr	= !plname
		
		if !ptr.type EQ 'PLOO' then

			!depth		= !ptr.height
			!listpnts	= !ptr.members

			!swriter.writerecord( !!wuXmlDouble( |Height|, !depth ) )

			--	...........................................
			--	局部坐标系下的边界点集合
			--
			!swriter.writerecord( '<Local-Points>'  )
			
			!idx = 1
			do !ptname values !listpnts
				!ptr	= !ptname
				!post	= !ptr.position
				!swriter.writerecord( !!wuXmlIndexPoint( |Point|, !idx, !post ) )
				!idx	= !idx + 1
			enddo
			
			!swriter.writerecord( '</Local-Points>'  )

			--	...........................................
			--
			--	GLOBAL 坐标系下的边界点集合
			--
			!swriter.writerecord( '<Points>'  )
			
			!idx = 1
			do !ptname values !listpnts
				!ptr	= !ptname
				!post	= !ptr.position.wrt( world )
				!swriter.writerecord( !!wuXmlIndexPoint( |Point|, !idx, !post ) )
				!idx	= !idx + 1
			enddo
			
			!swriter.writerecord( '</Points>'  )
			
			--	...........................................
			
		endif
	
	enddo

	!swriter.writerecord( '</GWall>' )

enddo

!swriter.writerecord( '</ListGWall>' )
!swriter.close( )

--	............................................................................

!!CE	= !currENT

